# Generated by Django 6.0.6 on 2026-07-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
