# Generated by Django 6.0.6 on 2026-07-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_consent_analytics',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cookie_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
